---
- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: CA Certificates
      apt:
        name: ca-certificates

    - name: Install curl
      apt:
        name: curl

    - name: Download JDK
      get_url:
        url: https://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jdk-8u211-linux-x64.tar.gz
        headers: "Cookie:oraclelicense=accept-securebackup-cookie"
        dest: /tmp/jdk-8u211-linux-x64.tar.gz

    - name: Extract JDK tarball
      unarchive:
        src: /tmp/jdk-8u211-linux-x64.tar.gz
        dest: /opt
        creates: /opt/jdk1.8.0_211/
        remote_src: yes

- hosts: standalone
  roles:
    - role: ansible-role-jboss
      jboss_properties:
        jboss.bind.address: "0.0.0.0"
        jboss.bind.address.management: "0.0.0.0"

